### PR TITLE
Changed visibility in order to allow reads

### PR DESCRIPTION
**Pull request by anfelbar**
In order to build [PR](https://github.com/EngFlow/example/pull/30)

### CODE REVIEW

**Comment by anfelbar** [comment]
@Yannic WDYT?

**Comment by jayconrod** [comment]
I think it should be possible to build the example by depending on the `proto_library` targets with `srcs` which are already public and not these targets.

On the other hand, I would think all targets in this is repo would be public. @Yannic would have more context.

**Comment by Yannic** [comment]
Yes, we should use the fine-grained `proto_library` targets instead

**Comment by anfelbar** [comment]
You guys are right. Closing the PR.

**Pull request closed without merging**
